name = "pagina-da-escard"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "escard-db"
database_id = "2cd7518f-435d-4fcb-9622-349404dd5323"
